services:
  frontend:
    build:
      context: ./show-me-the-money-frontend
    ports:
      - "5000:80"

  backend:
    build:
      context: ./show-me-the-money-backend
    ports:
      - "8000:8000"
    depends_on:
      - xero_api  

  xero_api:
    image: jaypeng2015/show-me-the-money
    platform: linux/arm64
    ports:
      - "3000:3000"